// meshyy — what the emulator is asked to draw when a session opens.
// Copyright (c) 2026 Aaron Character. MIT licence — see LICENSE.
//
// Measurement first, fix second. The reported symptom is a single visible flash when a
// session starts, and the previous attempt at it — coalesce the replay in the client —
// was written before anyone had counted what the client actually receives. It buffered
// forever when a replay was empty and swallowed live output, and two tests caught it.
//
// So this counts. A terminal repaints once per delivery it is handed; a flash is a
// sequence of deliveries that each leave the screen in a different intermediate state.
// The number that matters is therefore "how many separate deliveries carry the replay",
// and whether any of them clears.

import Foundation
import MeshyyCore
import Testing
@testable import MeshyyKit

extension MeshyyKitSuite {
@Suite("Session-start paint")
struct SessionStartPaintTests {

    /// One delivery of bytes to the emulator, as the client would make it.
    private struct Paint {
        let at: TimeInterval
        let bytes: [UInt8]
        var text: String { String(decoding: bytes, as: UTF8.self) }
        /// A delivery that erases before drawing is a visible blank frame if anything
        /// follows it in a later delivery.
        var clears: Bool {
            for erase in ["\u{1B}[2J", "\u{1B}[3J", "\u{1B}c", "\u{1B}[H\u{1B}[J"]
            where text.contains(erase) { return true }
            return false
        }
    }

    private func record(
        _ session: MeshyySession,
        from bootstrap: BootstrapResponse,
        settlingFor settle: Duration
    ) async throws -> [Paint] {
        let started = Date()
        let paints = Recorder()
        let collector = Task {
            for await event in await session.events {
                switch event {
                case .output(let bytes):
                    await paints.append(Paint(at: Date().timeIntervalSince(started), bytes: bytes))
                default:
                    break
                }
            }
        }
        defer { collector.cancel() }
        try await session.attach(bootstrap: bootstrap, sshHost: "127.0.0.1")
        try await Task.sleep(for: settle)
        return await paints.all
    }

    private actor Recorder {
        var all: [Paint] = []
        func append(_ paint: Paint) { all.append(paint) }
    }

    /// THE PROPERTY. A resume must reach the client as ONE `.output`.
    ///
    /// Not "few": one. Every extra delivery is another frame the user can see, and the
    /// replay is by definition a screen that was already whole — there is no reason to
    /// show it being assembled. Live output that arrives afterwards is a separate matter
    /// and must NOT be held back, which is what the previous attempt got wrong.
    ///
    /// The geometry reset is deliberately NOT counted here. It is a separate event
    /// carrying locally generated bytes, and folding it into `.output` to save a
    /// delivery breaks the byte-exactness a resume depends on — measured, by the
    /// reattach test, as 13 unexpected bytes. Merging those two deliveries is the
    /// renderer's job, where it costs nothing.
    @Test("A replay reaches the client as a single output")
    func replayIsOnePaint() async throws {
        try await withHarness(child: .shell) { daemon in
            let name = "paint-replay"

            // First client: make some scrollback, then leave. `detach` keeps the shell
            // and its ring buffer, which is what gives the second client a replay.
            let first = MeshyySession(size: TerminalSize(cols: 80, rows: 24))
            let firstCollector = Task { for await _ in await first.events {} }
            try await first.attach(bootstrap: try daemon.bootstrap(session: name), sshHost: "127.0.0.1")
            try await first.send(Array("printf 'line-%s\\n' 1 2 3 4 5 6 7 8 9 10\n".utf8))
            try await Task.sleep(for: .milliseconds(800))
            await first.detach(reason: "measuring the next attach")
            firstCollector.cancel()

            // Second client, resuming from nothing: the daemon replays the buffer.
            let second = MeshyySession(size: TerminalSize(cols: 80, rows: 24))
            let paints = try await record(
                second, from: try daemon.bootstrap(session: name), settlingFor: .milliseconds(900)
            )
            await second.shutdown(reason: "measured")

            let carrying = paints.filter { !$0.bytes.isEmpty }
            let summary = carrying.enumerated()
                .map { "#\($0.offset) at \(Int($0.element.at * 1000))ms: \($0.element.bytes.count)B\($0.element.clears ? " CLEARS" : "")" }
                .joined(separator: ", ")

            #expect(!carrying.isEmpty, "the replay never arrived at all — \(summary)")
            // The whole replay in the FIRST delivery. Not "exactly one delivery in
            // total": the attach also forces a SIGWINCH so a program that drifted out of
            // sync re-reads the size, and that redraw is live output arriving right
            // behind the replay. It is a separate paint by nature and must not be held
            // back — the property here is that the RESTORED SCREEN is not assembled in
            // front of the user, which is what the flash was.
            let firstPaint = carrying.first.map(\.text) ?? ""
            let missing = (1...10).map { "line-\($0)" }.filter { !firstPaint.contains($0) }
            #expect(missing.isEmpty, """
                the replay was split across deliveries — the first one is missing \
                \(missing.joined(separator: ", ")), so the user watches the restored screen \
                assemble instead of appearing whole. Deliveries: \(summary)
                """)
        }
    }

    /// The regression the previous attempt shipped: with an EMPTY replay it buffered
    /// waiting for an end it would never see, and live output never reached the screen.
    ///
    /// A fresh session is the common case — every first connect to a host — so this is
    /// the one that must not break.
    @Test("A fresh session still delivers live output promptly")
    func freshSessionIsNotHeldBack() async throws {
        try await withHarness(child: .shell) { daemon in
            let session = MeshyySession(size: TerminalSize(cols: 80, rows: 24))
            let paints = Recorder()
            let started = Date()
            let collector = Task {
                for await event in await session.events {
                    if case .output(let bytes) = event {
                        await paints.append(Paint(at: Date().timeIntervalSince(started), bytes: bytes))
                    }
                }
            }
            defer { collector.cancel() }

            // Nothing to replay: this session has never existed before.
            try await session.attach(bootstrap: try daemon.bootstrap(session: "paint-fresh"), sshHost: "127.0.0.1")
            let marker = "FRESH" + "-OUTPUT-OK"
            try await session.send(Array("printf '%s%s\\n' 'FRESH' '-OUTPUT-OK'\n".utf8))

            var arrived = false
            let deadline = Date().addingTimeInterval(10)
            while Date() < deadline, !arrived {
                let text = await paints.all.map(\.text).joined()
                arrived = text.contains(marker)
                if !arrived { try await Task.sleep(for: .milliseconds(100)) }
            }
            await session.shutdown(reason: "measured")

            #expect(arrived, """
                live output never reached the emulator on a session with no replay. A \
                coalescing scheme that waits for an end-of-replay signal must still flush when \
                the replay is empty — this is exactly the regression the first attempt shipped
                """)
        }
    }
}
}
